#!/usr/bin/python
from datetime import datetime

t = [5, 3, 2, 6, 10, 11]
print t

def dupa(t):
    t[0] = 4
    print t
    return 0

dupa(t[:])
print t


x = datetime.now()
print "Hello"
y = datetime.now()
print (y - x) / 3
